<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>home</title>

   <!-- swiper css link  -->
   <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

   <!-- font awesome cdn link  -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

   <!-- custom css file link  -->
   <link rel="stylesheet" href="style.css">

</head>
<body>
   
<!-- header section starts  -->

<section class="header">

   <a href="home.PHP" class="logo">Karnataka Tourism Management</a>

   <nav class="navbar">
      <a href="home.php">Home</a>
      <a href="about.php">Experience</a>
      <a href="package.php">Packages</a>
      <a href="book.php">Book</a>
   </nav>

   <div id="menu-btn" class="fas fa-bars"></div>

</section>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home">

   <div class="swiper home-slider">

      <div class="swiper-wrapper">

         <div class="swiper-slide slide" style="background:url(home-slide1.jpg) no-repeat">
            <div class="content">
               <span>Explore, Discover, Travel</span>
               <h3>Karnataka Tourism</h3>
               <a href="package.PHP" class="btn">Explore Further</a>
            </div>
         </div>

         <div class="swiper-slide slide" style="background:url(home-slide-2.jpg) no-repeat">
            <div class="content">
               <span>Explore, Discover, Travel</span>
               <h3>Visit the Temple City</h3>
               <a href="package.PHP" class="btn">Explore Further</a>
            </div>
         </div>

         <div class="swiper-slide slide" style="background:url(home-slide-3.jpg) no-repeat">
            <div class="content">
               <span></span>
               <h3>Coastal Bliss</h3>
               <a href="package.PHP" class="btn">Explore Further</a>
            </div>
         </div>
         
      </div>

      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>

   </div>

</section>

<!-- home section ends -->

<!-- services section starts  -->

<section class="services">

   <h1 class="heading-title"> Our Services </h1>

   <div class="box-container">

      <div class="box">
         <img src="icon-1.png" alt="">
         <h3>Adventure</h3>
      </div>

      <div class="box">
         <img src="icon-2.png" alt="">
         <h3>Tour guide</h3>
      </div>

      <div class="box">
         <img src="icon-3.png" alt="">
         <h3>Trekking</h3>
      </div>

      <div class="box">
         <img src="icon-4.png" alt="">
         <h3>Camp Fire</h3>
      </div>

      <div class="box">
         <img src="icon-5.png" alt="">
         <h3>Off Road</h3>
      </div>

      <div class="box">
         <img src="icon-6.png" alt="">
         <h3>Camping</h3>
      </div>

   </div>

</section>

<!-- services section ends -->

<!-- home about section starts  -->

<section class="home-about">

   <div class="image">
      <img src="about-img.jpg" alt="">
   </div>

   <div class="content">
      <h3>About Us</h3>
      <p>Embark on a journey through our story, passion, and wanderlust</p>
      <a href="about.PHP" class="btn">Read more</a>
   </div>

</section>

<!-- home about section ends -->

<!-- home packages section starts  -->

<section class="home-packages">

   <h1 class="heading-title"> our packages </h1>

   <div class="box-container">

      <div class="box">
         <div class="image">
            <img src="image1.jpg" alt="">
         </div>
         <div class="content">
            <h3>Hampi</h3>
            <p>Where ancient ruins meet modern wanderers</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image2.jpg" alt="">
         </div>
         <div class="content">
            <h3>Mysore Zoo</h3>
            <p>A wild sanctuary in the heart of heritage</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>
      
      <div class="box">
         <div class="image">
            <img src="image3.jpg" alt="">
         </div>
         <div class="content">
            <h3>Golgumbaz</h3>
            <p>Architectural marvel echoing the tales of history</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

   </div>

   <div class="load-more"> <a href="package.php" class="btn">load more</a> </div>

</section>

<!-- home packages section ends -->

<!-- home offer section starts  -->

<section class="home-offer">
   <div class="content">
      <h3>upto 50% off</h3>
      <p>Hurry up!!Book now for best offers</p>
      <a href="book.PHP" class="btn">book now</a>
   </div>
</section>

<!-- home offer section ends -->

<!-- footer section starts  -->

<section class="footer">

   <div class="box-container">

      <div class="box">
         <h3>quick links</h3>
         <a href="home.PHP"> <i class="fas fa-angle-right"></i> Home</a>
         <a href="about.PHP"> <i class="fas fa-angle-right"></i> About</a>
         <a href="package.PHP"> <i class="fas fa-angle-right"></i> Packages</a>
         <a href="book.PHP"> <i class="fas fa-angle-right"></i> Book</a>
      </div>

      <div class="box">
         <h3>extra links</h3>
         <a href="#"> <i class="fas fa-angle-right"></i> ask questions</a>
         <a href="#"> <i class="fas fa-angle-right"></i> about us</a>
         <a href="#"> <i class="fas fa-angle-right"></i> privacy policy</a>
         <a href="#"> <i class="fas fa-angle-right"></i> terms of use</a>
      </div>

      <div class="box">
         <h3>contact info</h3>
         <a href="#"> <i class="fas fa-phone"></i> +123-456-7890 </a>
         <a href="#"> <i class="fas fa-phone"></i> +111-222-3333 </a>
         <a href="#"> <i class="fas fa-envelope"></i> nikhi@gmail.com </a>
         <a href="#"> <i class="fas fa-map"></i> kota,karnataka - 576221</a>
      </div>

      <div class="box">
         <h3>follow us</h3>
         <a href="#"> <i class="fab fa-facebook-f"></i> facebook </a>
         <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
         <a href="#"> <i class="fab fa-instagram"></i> instagram </a>
         <a href="#"> <i class="fab fa-linkedin"></i> linkedin </a>
      </div>

   </div>

   <div class="credit">  <span> [all rights reserved]</span> </div>

</section>

<!-- footer section ends -->

<!-- swiper js link  -->
<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

<!-- custom js file link  -->
<script src="script.js"></script>

</body>
</html>