<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Packages</title>

   <!-- swiper css link  -->
   <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

   <!-- font awesome cdn link  -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

   <!-- custom css file link  -->
   <link rel="stylesheet" href="style.css">

</head>
<body>
   
<!-- header section starts  -->

<section class="header">

   <a href="home.PHP" class="logo">travel.</a>

   <nav class="navbar">
      <a href="home.PHP">Home</a>
      <a href="about.PHP">About</a>
      <a href="package.PHP">Package</a>
      <a href="book.PHP">Book</a>
   </nav>

   <div id="menu-btn" class="fas fa-bars"></div>

</section>

<!-- header section ends -->

<div class="heading" style="background:url(header-bg2.png) no-repeat">
   <h1>packages</h1>
</div>

<!-- packages section starts  -->

<section class="Packages">

   <h1 class="heading-title">Top destinations</h1>

   <div class="box-container">

      <div class="box">
         <div class="image">
            <img src="image1.jpg" alt="">
         </div>
         <div class="content">
            <h3>Hampi</h3>
            <p>Where Ancient Ruins Meet Modern Wanderers</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image2.jpg" alt="">
         </div>
         <div class="content">
            <h3>Mysore zoo</h3>
            <p>A Wild Sanctuary In The Heart Of Heritage</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image3.jpg" alt="">
         </div>
         <div class="content">
            <h3>Golgumbaz</h3>
            <p>Architectural Marvel Echoing The Tales Of History</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image4.jpg" alt="">
         </div>
         <div class="content">
            <h3>Nagarahole Tiger Reserve</h3>
            <p>untamed beauty, a sanctuary where nature thrives and wildlife roams freely amidst lush greenery</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image5.jpg" alt="">
         </div>
         <div class="content">
            <h3>Lalbagh Botanical Garden</h3>
            <p> verdant oasis in the heart of the bustling city,</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image6.jpg" alt="">
         </div>
         <div class="content">
            <h3>Jog Falls</h3>
            <p>breathtaking cascade of nature's grandeur, plummeting gracefully from towering heights </p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image7.jpg" alt="">
         </div>
         <div class="content">
            <h3>Mysore Palace</h3>
            <p>A stunning architectural marvel in the heart of Mysore city,</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image8.jpg" alt="">
         </div>
         <div class="content">
            <h3>Murudeshwara Temple</h3>
            <p> Nestled along the serene coastline of Karnataka, is a sacred site revered by devotees </p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image9.jpg" alt="">
         </div>
         <div class="content">
            <h3>Chikkmagaluru</h3>
            <p>Nestled in the heart of the Western Ghats, is a haven for nature lovers and coffee aficionados</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image10.jpg" alt="">
         </div>
         <div class="content">
            <h3>Saligrama Kayaking Point</h3>
            <p>hidden gem nestled along the serene banks of the Saligrama River in Karnataka</p>
            <a href="book.PHP" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image11.jpg" alt="">
         </div>
         <div class="content">
            <h3>Krishna Mutt</h3>
            <p>quaint town of Udupi, Karnataka, is a revered pilgrimage site and a symbol of devotion and spirituality</p>
            <a href="book.php" class="btn">book now</a>
         </div>
      </div>

      <div class="box">
         <div class="image">
            <img src="image12.jpg" alt="">
         </div>
         <div class="content">
            <h3>Malpe Beach</h3>
            <p>nestled along the azure coast of Karnataka, is a picturesque haven renowned for its golden sands, crystal-clear waters,</p>
            <a href="book.php" class="btn">book now</a>
         </div>
      <div class="box">
         <div class="image">
            <img src="image13.jpg" alt="">
         </div>
         <div class="content">
            <h3>Dandeli</h3>
            <p>Dandeli, nestled in the Western Ghats of Karnataka, is renowned for its lush forests, adventure activities, and wildlife sanctuaries</p>
            <a href="book.php" class="btn">book now</a>
         </div>
      </div>
      <div class="box">
         <div class="image">
            <img src="image-14.jpg" alt="">
         </div>
         <div class="content">
            <h3>Karwar Beach</h3>
            <p>Karwar Beach: A serene coastal escape with stunning sunsets</p>
            <a href="book.php" class="btn">book now</a>
         </div>
         
   </div>

   <div class="load-more"><span class="btn">load more</span></div>

</section>

<!-- packages section ends -->



<!-- footer section starts  -->

<section class="footer">

   <div class="box-container">

      <div class="box">
         <h3>quick links</h3>
         <a href="home.PHP"> <i class="fas fa-angle-right"></i> Home</a>
         <a href="about.PHP"> <i class="fas fa-angle-right"></i> About</a>
         <a href="package.PHP"> <i class="fas fa-angle-right"></i> Packages</a>
         <a href="book.PHP"> <i class="fas fa-angle-right"></i> Book</a>
      </div>

      <div class="box">
         <h3>extra links</h3>
         <a href="#"> <i class="fas fa-angle-right"></i> ask questions</a>
         <a href="#"> <i class="fas fa-angle-right"></i> about us</a>
         <a href="#"> <i class="fas fa-angle-right"></i> privacy policy</a>
         <a href="#"> <i class="fas fa-angle-right"></i> terms of use</a>
      </div>

      <div class="box">
         <h3>contact info</h3>
         <a href="#"> <i class="fas fa-phone"></i> +123-456-7890 </a>
         <a href="#"> <i class="fas fa-phone"></i> +111-222-3333 </a>
         <a href="#"> <i class="fas fa-envelope"></i> nikhi@gmail.com </a>
         <a href="#"> <i class="fas fa-map"></i> kota,karnataka - 400104 </a>
      </div>

      <div class="box">
         <h3>follow us</h3>
         <a href="#"> <i class="fab fa-facebook-f"></i> facebook </a>
         <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
         <a href="#"> <i class="fab fa-instagram"></i> instagram </a>
         <a href="#"> <i class="fab fa-linkedin"></i> linkedin </a>
      </div>

   </div>

   <div class="credit"> <span></span> [all rights reserved]</div>

</section>

<!-- footer section ends -->
<!-- swiper js link  -->
<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

<!-- custom js file link  -->
<script src="script.js"></script>

</body>
</html>